phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/75/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Anekal.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/76/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Hoskote.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/208/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Yelahanka.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/209/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Rajajinagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/210/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Chickpet.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/211/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Chamarajpet.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/212/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Malleshwaram.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/215/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Shivajinagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/216/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Basavanagudi.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/217/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Gandhinagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/218/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Shantinagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/219/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Jayanagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/246/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_KR_Puram.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/247/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Rajarajeshwarinagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/248/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Dasarahalli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/249/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Mahalakshmi_Layout.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/250/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Hebbal.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/251/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Pulakeshinagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/252/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Sarvajna_Nagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/253/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_CV_Raman_Nagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/254/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Govindrajnagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/255/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Vijayanagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/256/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Padmanabhanagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/257/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_BTM_Layout.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/258/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Mahadevpura.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/259/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Bommanahalli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/260/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Bangalore_South.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/261/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Byatrayanapura.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/262/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MLA_Yashwantpura.pdf
echo “ MLA Kannada done”    
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/1/227/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MP_Chikkaballapur.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/1/238/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MP_Bangalore_North.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/1/245/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MP_Bangalore_South.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/1/263/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MP_Bangalore_Rural.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/1/264/1/2 /home/megha/www/klpreports/forprint/fin/Kannada/MP_Bangalore_Central.pdf
echo “ MP Kannada done”    
