phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/75/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Anekal.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/76/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Hoskote.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/208/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Yelahanka.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/209/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Rajajinagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/210/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Chickpet.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/211/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Chamarajpet.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/212/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Malleshwaram.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/215/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Shivajinagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/216/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Basavanagudi.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/217/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Gandhinagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/218/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Shantinagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/219/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Jayanagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/246/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_KR_Puram.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/247/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Rajarajeshwarinagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/248/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Dasarahalli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/249/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Mahalakshmi_Layout.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/250/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Hebbal.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/251/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Pulakeshinagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/252/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Sarvajna_Nagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/253/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_CV_Raman_Nagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/254/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Govindrajnagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/255/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Vijayanagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/256/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Padmanabhanagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/257/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_BTM_Layout.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/258/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Mahadevpura.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/259/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Bommanahalli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/260/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Bangalore_South.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/261/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Byatrayanapura.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/262/2/4	/home/megha/www/klpreports/forprint/lib/English/MLA_Yashwantpura.pdf
echo “ MLA English done”				
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/1/227/2/4	/home/megha/www/klpreports/forprint/lib/English/MP_Chikkaballapur.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/1/238/2/4	/home/megha/www/klpreports/forprint/lib/English/MP_Bangalore_North.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/1/245/2/4	/home/megha/www/klpreports/forprint/lib/English/MP_Bangalore_South.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/1/263/2/4	/home/megha/www/klpreports/forprint/lib/English/MP_Bangalore_Rural.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/1/264/2/4	/home/megha/www/klpreports/forprint/lib/English/MP_Bangalore_Central.pdf
echo “ MP English done”				
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/75/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Anekal.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/76/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Hoskote.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/208/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Yelahanka.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/209/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Rajajinagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/210/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Chickpet.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/211/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Chamarajpet.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/212/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Malleshwaram.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/215/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Shivajinagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/216/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Basavanagudi.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/217/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Gandhinagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/218/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Shantinagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/219/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Jayanagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/246/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_KR_Puram.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/247/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Rajarajeshwarinagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/248/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Dasarahalli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/249/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Mahalakshmi_Layout.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/250/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Hebbal.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/251/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Pulakeshinagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/252/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Sarvajna_Nagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/253/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_CV_Raman_Nagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/254/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Govindrajnagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/255/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Vijayanagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/256/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Padmanabhanagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/257/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_BTM_Layout.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/258/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Mahadevpura.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/259/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Bommanahalli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/260/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Bangalore_South.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/261/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Byatrayanapura.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/2/262/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MLA_Yashwantpura.pdf
echo “ MLA Kannada done”    
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/1/227/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MP_Chikkaballapur.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/1/238/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MP_Bangalore_North.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/1/245/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MP_Bangalore_South.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/1/263/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MP_Bangalore_Rural.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/1/264/1/4 /home/megha/www/klpreports/forprint/lib/Kannada/MP_Bangalore_Central.pdf
echo “ MP Kannada done”    
