common_queries = {
'get_mp_const':"select const_ward_name,id from tb_electedrep_master where parent=4 and const_ward_type='MP Constituency' and status='active' order by const_ward_name;",
'get_mla_const':"select const_ward_name,id from tb_electedrep_master where parent in (4,5) and const_ward_type='MLA Constituency' and status='active' order by const_ward_name;",
'get_corporator_const':"select const_ward_name,id from tb_electedrep_master and const_ward_type='Ward' and parent='3' and status='active' order by const_ward_name;",
'get_dise_avg_blore':"select distinct dfa.df_metric as a1, count(distinct dfa.dise_code),dfa.df_group as a2 from vw_dise_facility_agg dfa, tb_school_electedrep tse,vw_school_dise vsd where tse.sid=vsd.sid and vsd.dise_code=dfa.dise_code and dfa.score=100 group by dfa.df_metric,dfa.df_group;",
'get_dise_count_blore':"select count(distinct dfa.dise_code) from vw_dise_facility_agg dfa, tb_school_electedrep tse,vw_school_dise vsd where tse.sid=vsd.sid and vsd.dise_code=dfa.dise_code;",
'get_sch_count_blore':"select count(distinct tse.sid) from tb_school_electedrep tse where heirarchy=1;",
'get_ai_avg_blore':"select distinct aia.ai_metric as a1, count(distinct aia.sid),aia.ai_group as a2 from vw_ang_infra_agg aia, tb_school_electedrep tse where tse.sid=aia.sid and aia.perc_score=100 group by aia.ai_metric,aia.ai_group;",
'get_ai_count_blore':"select count(distinct aia.sid) from vw_ang_infra_agg aia, tb_school_electedrep tse where tse.sid=aia.sid;",
'get_ang_count_blore':"select count(distinct tse.sid) from tb_school_electedrep tse where heirarchy=2;",
'get_mp_ids':"select distinct mp.const_ward_name, se.mp_const_id, se.bang_yn from tb_school_electedrep se,tb_electedrep_master mp where mp.id = se.mp_const_id;",
'get_mla_ids':"select distinct mla.const_ward_name, se.mla_const_id, se.bang_yn from tb_school_electedrep se,tb_electedrep_master mla where mla.id = se.mla_const_id;",
'get_ward_ids':"select distinct ward.const_ward_name, se.ward_id, se.bang_yn from tb_school_electedrep se,tb_electedrep_master ward where ward.id = se.ward_id;",
'get_schdist':"select distinct upper(district) as district,dist_id, case when dist_id=8877 or dist_id=8773 then 1 else 2 end as bang_yn from vw_school_dise where sid in (select sid from tb_school_electedrep ) and type=1;",
'get_preschdist':"select distinct upper(district) as district,dist_id, case when dist_id=8877 or dist_id=8773 then 1 else 2 end as bang_yn from vw_school_dise where sid in (select sid from tb_school_electedrep ) and type=2;",
'get_block':"select distinct upper(block) as block,blck_id, case when dist_id=8877 or dist_id=8773 then 1 else 2 end as bang_yn from vw_school_dise where sid in (select sid from tb_school_electedrep ) and type=1;",
'get_cluster':"select distinct upper(clust) as clust,clst_id, case when dist_id=8877 or dist_id=8773 then 1 else 2 end as bang_yn from vw_school_dise where sid in (select sid from tb_school_electedrep ) and type=1;",
'get_proj':"select distinct upper(block) as block,blck_id, case when dist_id=8877 or dist_id=8773 then 1 else 2 end as bang_yn from vw_school_dise where sid in (select sid from tb_school_electedrep ) and type=2;",
'get_circle':"select distinct upper(clust) as clust,clst_id, case when dist_id=8877 or dist_id=8773 then 1 else 2 end as bang_yn from vw_school_dise where sid in (select sid from tb_school_electedrep ) and type=2;",
}

mla_queries = {
'mla_gend_sch':"select tssc.sex, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mla_const_id=$s and heirarchy=1 group by tssc.sex",
'mla_gend_presch':"select tssc.sex, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mla_const_id=$s and heirarchy=2 and tssc.cat='Anganwadi' group by tssc.sex",
'mla_mt_sch':"select tssc.mt, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mla_const_id=$s and heirarchy=1 group by tssc.mt;",
'mla_mt_presch':"select tssc.mt, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mla_const_id=$s and heirarchy=2 and tssc.cat='Anganwadi' group by tssc.mt;",
'mla_schcount':"select count(distinct tssc.sid) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mla_const_id=$s and tse.heirarchy=1;",
'mla_preschcount':"select count(distinct tssc.sid) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mla_const_id=$s and tse.heirarchy=2 and tssc.sid=tse.sid and tssc.cat='Anganwadi';",
'mla_const_details':"select elec_comm_code, const_ward_name , current_elected_rep, const_ward_type, neighbours,current_elected_party from tb_electedrep_master where const_ward_type='MLA Constituency' and id=$s;",
'mla_moi_sch':"select distinct tssc.moi as a1, count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mla_const_id=$s and heirarchy=1 group by tssc.moi;",
#'mla_moi_presch':"select distinct tssc.moi as a1, count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mla_const_id=$s and heirarchy=2 and tssc.cat='Anganwadi' group by tssc.moi;",
'mla_cat_sch':"select distinct tssc.cat as a1, count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mla_const_id=$s and heirarchy=1 group by tssc.cat;",
'mla_cat_presch':"select distinct tssc.cat as a1, count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mla_const_id=$s and heirarchy=2 and tssc.cat='Anganwadi' group by tssc.cat;",
'mla_neighbour_sch':"select distinct tem.const_ward_name,count(distinct tssc.sid) from tb_school_stu_counts tssc, tb_school_electedrep tse, tb_electedrep_master tem where tse.mla_const_id = tem.id and tse.sid=tssc.sid and tem.elec_comm_code in $s and tse.heirarchy=1 group by tem.const_ward_name;",
'mla_neighbour_presch':"select distinct tem.const_ward_name,count(distinct tssc.sid) from tb_school_stu_counts tssc, tb_school_electedrep tse, tb_electedrep_master tem where tse.mla_const_id = tem.id and tse.sid=tssc.sid and tem.elec_comm_code in $s and tse.heirarchy=2 and tssc.cat='Anganwadi' group by tem.const_ward_name;",
'mla_neighbour_gendsch':"select distinct tem.const_ward_name, tssc.sex, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse,tb_electedrep_master tem where tse.sid=tssc.sid and tse.mla_const_id = tem.id and tem.elec_comm_code in $s and heirarchy=1 group by tem.const_ward_name,tssc.sex",
'mla_neighbour_gendpresch':"select distinct tem.const_ward_name, tssc.sex, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse,tb_electedrep_master tem where tse.sid=tssc.sid and tse.mla_const_id = tem.id and tem.elec_comm_code in $s and heirarchy=2 and tssc.cat='Anganwadi' group by tem.const_ward_name,tssc.sex",
'mla_enrol_sch':"select distinct tssc.cat as a1, sum(tssc.numstu)/count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mla_const_id=$s and heirarchy=1 group by tssc.cat;",
'mla_enrol_presch':"select distinct tssc.cat as a1, sum(tssc.numstu)/count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mla_const_id=$s and heirarchy=2 and tssc.cat='Anganwadi' group by tssc.cat;",
'mla_tlmgrant_sch':"select tem.const_ward_name, vpd.grant_type, vpd.grant_amount, vpd.grant_amount* sum(vdf.teacher_count) as total_grant from tb_electedrep_master tem,tb_school_electedrep tse, vw_paisa_data vpd, vw_school_dise vsd, vw_dise_info vdf where tem.id=tse.mla_const_id and tse.sid=vsd.sid and vdf.dise_code=vsd.dise_code and vpd.criteria='teacher_count' and tse.mla_const_id=$s group by tem.const_ward_name, vpd.grant_type, vpd.grant_amount;",
'mla_mtncgrant_sch':"select tem.const_ward_name, vpd2.grant_type, CASE WHEN mvdf.operator='gt' THEN 'With more than 3 classrooms ' ELSE 'With 3 classrooms or fewer ' END as classroom_count, count(distinct tse.sid), vpd2.grant_amount * count(distinct tse.sid) as total_grant from (select vdf.dise_code as dise_id, CASE WHEN vdf.classroom_count <= CAST (vpd.factor AS INT) THEN 'lt' ELSE 'gt' END as operator from vw_paisa_data vpd, vw_dise_info vdf where vpd.criteria='classroom_count') AS mvdf, tb_electedrep_master tem, tb_school_electedrep tse, vw_school_dise vsd, vw_paisa_data vpd2 where tem.id=tse.mla_const_id and tse.sid = vsd.sid and mvdf.dise_id=vsd.dise_code and mvdf.operator = vpd2.operator and tse.mla_const_id=$s group by tem.const_ward_name, vpd2.grant_type, mvdf.operator, vpd2.grant_amount order by tem.const_ward_name;",
'mla_annualgrant_sch':"select tem.const_ward_name, vsd.cat, vpd.grant_type, count(distinct tse.sid), vpd.grant_amount * count(distinct tse.sid) as total_grant from tb_electedrep_master tem, tb_school_electedrep tse, vw_school_dise vsd, vw_paisa_data vpd where tem.id=tse.mla_const_id and tse.sid=vsd.sid and vpd.criteria='school_cat' and vpd.factor = vsd.cat::text and tse.mla_const_id=$s group by tem.const_ward_name, vsd.cat,vpd.grant_type,vpd.grant_amount order by tem.const_ward_name, vsd.cat;",
'mla_neighbor_annual':"select tem.const_ward_name, vsd.cat, vpd.grant_type, vpd.grant_amount * count(distinct tse.sid) as total_grant from tb_electedrep_master tem, tb_school_electedrep tse, vw_school_dise vsd, vw_paisa_data vpd where tem.id=tse.mla_const_id and tse.sid=vsd.sid and vpd.criteria='school_cat' and vpd.factor = vsd.cat::text and tem.elec_comm_code in $s group by tem.const_ward_name, vsd.cat,vpd.grant_type,vpd.grant_amount order by tem.const_ward_name, vsd.cat;",
'mla_neighbor_tlm':"select tem.const_ward_name, vpd.grant_type, vpd.grant_amount, vpd.grant_amount* sum(vdf.teacher_count) as total_grant from tb_electedrep_master tem,tb_school_electedrep tse, vw_paisa_data vpd, vw_school_dise vsd, vw_dise_info vdf where tem.id=tse.mla_const_id and tse.sid=vsd.sid and vdf.dise_code=vsd.dise_code and vpd.criteria='teacher_count' and tem.elec_comm_code in $s group by tem.const_ward_name, vpd.grant_type, vpd.grant_amount;",
'mla_neighbor_mntnc':"select tem.const_ward_name, vpd2.grant_type, CASE WHEN mvdf.operator='gt' THEN 'With more than 3 classrooms ' ELSE 'With 3 classrooms or fewer ' END as classroom_count, vpd2.grant_amount * count(distinct tse.sid) as total_grant from (select vdf.dise_code as dise_id, CASE WHEN vdf.classroom_count <= CAST (vpd.factor AS INT) THEN 'lt' ELSE 'gt' END as operator from vw_paisa_data vpd, vw_dise_info vdf where vpd.criteria='classroom_count') AS mvdf, tb_electedrep_master tem, tb_school_electedrep tse, vw_school_dise vsd, vw_paisa_data vpd2 where tem.id=tse.mla_const_id and tse.sid = vsd.sid and mvdf.dise_id=vsd.dise_code and mvdf.operator = vpd2.operator and tem.elec_comm_code in $s group by tem.const_ward_name, vpd2.grant_type, mvdf.operator, vpd2.grant_amount order by tem.const_ward_name;",
'mla_abs_schcount':"select count(distinct tse.sid) from tb_school_electedrep tse where tse.mla_const_id=$s and tse.heirarchy=1;",
'mla_abs_preschcount':"select count(distinct tse.sid) from tb_school_electedrep tse where tse.mla_const_id=$s and tse.heirarchy=2;",
'mla_fin_schcount':"select count(distinct tse.sid) from vw_school_dise vsd, tb_school_electedrep tse where vsd.sid=tse.sid and tse.mla_const_id=$s and tse.heirarchy=1;",
'mla_ang_infra':"select distinct aia.ai_metric, count(distinct aia.sid),aia.ai_group from vw_ang_infra_agg aia, tb_school_electedrep tse where tse.sid=aia.sid and tse.mla_const_id=$s and aia.perc_score=100 group by aia.ai_metric,aia.ai_group;",
'mla_infra_count':"select count(distinct aia.sid) from vw_ang_infra_agg aia, tb_school_electedrep tse where tse.sid=aia.sid and tse.mla_const_id=$s;",
'mla_dise_facility':"select distinct dfa.df_metric, count(distinct dfa.dise_code),dfa.df_group from vw_dise_facility_agg dfa, tb_school_electedrep tse,vw_school_dise vsd where tse.sid=vsd.sid and vsd.dise_code=dfa.dise_code and tse.mla_const_id=$s and dfa.score=100 group by dfa.df_metric,dfa.df_group;",
'mla_dise_count':"select count(distinct dfa.dise_code) from vw_dise_facility_agg dfa, tb_school_electedrep tse,vw_school_dise vsd where tse.sid=vsd.sid and vsd.dise_code=dfa.dise_code and tse.mla_const_id=$s;",
'mla_lib_count':"select count(distinct li.sid) from vw_libinfra li, tb_school_electedrep tse where tse.sid=li.sid and tse.mla_const_id=$s;",
'mla_lib_status':"select li.libstatus, count(distinct li.sid) from vw_libinfra li, tb_school_electedrep tse where tse.sid=li.sid and tse.mla_const_id=$s group by li.libstatus;",
'mla_lib_summary':"select sum(numbooks) as totalbooks,sum(numracks) as totalracks,sum(numtables) as totaltables ,sum(numchairs) as totalchairs, sum(numcomputers) as totalcomps,sum(numups) as totalups from vw_libinfra li, tb_school_electedrep tse where tse.sid=li.sid and tse.mla_const_id=$s;",
'mla_neighbours_dise':"select distinct tem.const_ward_name, dfa.df_metric as a1, count(distinct dfa.dise_code),dfa.df_group as a2 from vw_dise_facility_agg dfa, tb_school_electedrep tse, tb_electedrep_master tem,vw_school_dise vsd where tse.sid=vsd.sid and vsd.dise_code=dfa.dise_code and tse.mla_const_id=tem.id and tem.elec_comm_code in $s and dfa.score=100 group by tem.const_ward_name, dfa.df_metric, dfa.df_group order by tem.const_ward_name,dfa.df_group;",
'mla_neighbours_anginfra':"select distinct tem.const_ward_name, aia.ai_metric as a1, count(distinct aia.sid), aia.ai_group as a2 from vw_ang_infra_agg aia, tb_school_electedrep tse,tb_electedrep_master tem where tse.sid=aia.sid and tse.mla_const_id=tem.id and tem.elec_comm_code in $s and aia.perc_score=100 group by tem.const_ward_name, aia.ai_metric,aia.ai_group order by tem.const_ward_name,aia.ai_group;",
'mla_neighbours_ai_count':"select tem.const_ward_name, count(distinct aia.sid) from vw_ang_infra_agg aia, tb_school_electedrep tse,tb_electedrep_master tem where tse.sid=aia.sid and tse.mla_const_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
'mla_neighbours_df_count':"select tem.const_ward_name, count(distinct dfa.dise_code) from vw_dise_facility_agg dfa, tb_school_electedrep tse,tb_electedrep_master tem,vw_school_dise vsd where tse.sid=vsd.sid and vsd.dise_code=dfa.dise_code and tse.mla_const_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
'mla_lib_lang':"select month, year, book_lang, sum(child_count) as txncount from vw_lib_lang_agg li, tb_school_electedrep tse where tse.sid=li.sid and tse.mla_const_id=$s and year='2011-2012' group by month, year, book_lang order by month, txncount desc;",
'mla_lib_level':"select month, year, book_level, sum(child_count) as txncount from vw_lib_level_agg li, tb_school_electedrep tse where tse.sid=li.sid and tse.mla_const_id=$s and year='2011-2012' group by month, year, book_level order by month, txncount desc;",
'mla_lib_class_lang':"select class as clas, book_lang, sum(child_count) as txncount from vw_lib_lang_agg li, tb_school_electedrep tse where tse.sid=li.sid and tse.mla_const_id=$s and year='2011-2012' group by class, book_lang order by class, txncount desc;",
'mla_lib_class_level':"select class as clas, book_level, sum(child_count) as txncount from vw_lib_level_agg li, tb_school_electedrep tse where tse.sid=li.sid and tse.mla_const_id=$s and year='2011-2012' group by class, book_level order by class, txncount desc;",
'mla_neighbours_libinfra':"select tem.const_ward_name, sum(li.numbooks) as count from vw_libinfra li, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=li.sid and tse.mla_const_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
'mla_neighbours_libschcount':"select tem.const_ward_name, count(distinct li.sid) as count from vw_libinfra li, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=li.sid and tse.mla_const_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
'mla_neighbours_libtxn':"select tem.const_ward_name, sum(llang.child_count) as count from vw_lib_lang_agg llang, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=llang.sid and tse.mla_const_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
'mla_neighbours_libstu':"select tem.const_ward_name, sum(tssc.numstu) as count from tb_school_stu_counts tssc, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=tssc.sid and tse.mla_const_id=tem.id and tse.heirarchy=1 and tem.elec_comm_code in $s group by tem.const_ward_name;",
'mla_sch_assess_class':"select vra.class as a1, vra.grade, sum(vra.stucount) as count from vw_reading_2011_agg vra, tb_school_electedrep tse where tse.sid=vra.sid and tse.mla_const_id=$s and vra.acyear='2011-2012' and vra.grade not in ('null','',' ') and vra.class is not null group by vra.class, vra.grade;",
'mla_sch_assess_bang':"select vra.grade, sum(vra.stucount) as count from vw_reading_2011_agg vra where vra.acyear='2011-2012' and vra.grade not in ('null','',' ') and vra.class is not null group by vra.grade;",
'mla_sch_assess_const':"select vra.grade, sum(vra.stucount) as count from vw_reading_2011_agg vra, tb_school_electedrep tse where tse.sid=vra.sid and tse.mla_const_id=$s and vra.acyear='2011-2012' and vra.grade not in ('null','',' ') and vra.class is not null group by vra.grade;",
'mla_sch_assess_gender':"select vra.gender as a1, vra.grade, sum(vra.stucount) as count from vw_reading_2011_agg vra, tb_school_electedrep tse where tse.sid=vra.sid and tse.mla_const_id=$s and vra.acyear='2011-2012' and vra.grade not in ('null','',' ') and vra.gender != 'err' group by vra.gender, vra.grade;",
'mla_sch_assess_cnt':"select count(distinct vra.sid) as schcount, sum(vra.stucount) as stucount from vw_reading_2011_agg vra, tb_school_electedrep tse where tse.sid=vra.sid and tse.mla_const_id=$s and vra.acyear='2011-2012';",
'mla_sch_assess_bang_cnt':"select count(distinct vra.sid) from vw_reading_2011_agg vra where vra.acyear='2011-2012';",
'mla_ang_assess_score':"select avg(vap.median_score * 100/ 56)::int as res from vw_angpre_2011_agg vap, tb_school_electedrep tse where tse.sid=vap.sid and tse.mla_const_id=$s;",
'mla_ang_assess_bang':"select avg(vap.median_score * 100/ 56)::int as res from vw_angpre_2011_agg vap;",
'mla_ang_assess_gender':"select vap.gender, avg(vap.median_score * 100/ 56)::int as res from vw_angpre_2011_agg vap, tb_school_electedrep tse where tse.sid=vap.sid and tse.mla_const_id=$s group by vap.gender;",
'mla_ang_assess_bang_gender':"select vap.gender, avg(vap.median_score * 100/ 56)::int as res from vw_angpre_2011_agg vap group by vap.gender;",
'mla_ang_assess_cnt':"select count(distinct vap.sid),sum(vap.stucount) from vw_angpre_2011_agg vap, tb_school_electedrep tse where tse.sid=vap.sid and tse.mla_const_id=$s;",
'mla_ang_assess_bang_cnt':"select count(distinct vap.sid) from vw_angpre_2011_agg vap;",
'mla_ang_assess_neighbor':'select tem.const_ward_name, vap.gender, avg(vap.median_score * 100/ 56)::int as res from vw_angpre_2011_agg vap, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=vap.sid and tse.mla_const_id=tem.id and tse.heirarchy=2 and tem.elec_comm_code in $s group by tem.const_ward_name,vap.gender;'
}

mp_queries = {
'mp_gend_sch':"select tssc.sex, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mp_const_id=$s and heirarchy=1 group by tssc.sex",
'mp_gend_presch':"select tssc.sex, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mp_const_id=$s and heirarchy=2 and tssc.cat='Anganwadi' group by tssc.sex",
'mp_mt_sch':"select tssc.mt, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mp_const_id=$s and heirarchy=1 group by tssc.mt;",
'mp_mt_presch':"select tssc.mt, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mp_const_id=$s and heirarchy=2 and tssc.cat='Anganwadi' group by tssc.mt;",
'mp_schcount':"select count(distinct tssc.sid) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mp_const_id=$s and tse.heirarchy=1;",
'mp_preschcount':"select count(distinct tssc.sid) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mp_const_id=$s and tse.heirarchy=2 and tssc.cat='Anganwadi';",
'mp_const_details':"select elec_comm_code, const_ward_name , current_elected_rep, const_ward_type, neighbours, current_elected_party from tb_electedrep_master where const_ward_type='MP Constituency' and id=$s;",
'mp_moi_sch':"select distinct tssc.moi as a1, count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mp_const_id=$s and heirarchy=1 group by tssc.moi;",
#'mp_moi_presch':"select distinct tssc.moi, count(distinct tssc.sid) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mp_const_id=$s and heirarchy=2 and tssc.cat='Anganwadi' group by tssc.moi;",
'mp_cat_sch':"select distinct tssc.cat as a1, count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mp_const_id=$s and heirarchy=1 group by tssc.cat;",
'mp_cat_presch':"select distinct tssc.cat as a1, count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mp_const_id=$s and heirarchy=2 and tssc.cat='Anganwadi' group by tssc.cat;",
'mp_neighbour_sch':"select distinct tem.const_ward_name,count(distinct tssc.sid) from tb_school_stu_counts tssc, tb_school_electedrep tse, tb_electedrep_master tem where tse.mp_const_id = tem.id and tse.sid=tssc.sid and tem.elec_comm_code in $s and tse.heirarchy=1 group by tem.const_ward_name;",
'mp_neighbour_presch':"select distinct tem.const_ward_name,count(distinct tssc.sid) from tb_school_stu_counts tssc, tb_school_electedrep tse, tb_electedrep_master tem where tse.mp_const_id = tem.id and tse.sid=tssc.sid and tem.elec_comm_code in $s and tse.heirarchy=2 and tssc.cat='Anganwadi' group by tem.const_ward_name;",
'mp_neighbour_gendsch':"select distinct tem.const_ward_name, tssc.sex, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse,tb_electedrep_master tem where tse.sid=tssc.sid and tse.mp_const_id = tem.id and tem.elec_comm_code in $s and heirarchy=1 group by tem.const_ward_name,tssc.sex",
'mp_neighbour_gendpresch':"select distinct tem.const_ward_name, tssc.sex, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse,tb_electedrep_master tem where tse.sid=tssc.sid and tse.mp_const_id = tem.id and tem.elec_comm_code in $s and heirarchy=2 and tssc.cat='Anganwadi' group by tem.const_ward_name,tssc.sex",
'mp_enrol_sch':"select distinct tssc.cat as a1, sum(tssc.numstu)/count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mp_const_id=$s and heirarchy=1 group by tssc.cat;",
'mp_enrol_presch':"select distinct tssc.cat as a1, sum(tssc.numstu)/count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.mp_const_id=$s and heirarchy=2 and tssc.cat='Anganwadi' group by tssc.cat;",
'mp_tlmgrant_sch':"select tem.const_ward_name, vpd.grant_type,vpd.grant_amount,vpd.grant_amount* sum(vdf.teacher_count) as total_grant from tb_electedrep_master tem,tb_school_electedrep tse, vw_paisa_data vpd, vw_school_dise vsd, vw_dise_info vdf where tem.id=tse.mp_const_id and tse.sid=vsd.sid and vdf.dise_code=vsd.dise_code and vpd.criteria='teacher_count' and tse.mp_const_id=$s group by tem.const_ward_name, vpd.grant_type, vpd.grant_amount;",
'mp_mtncgrant_sch':"select tem.const_ward_name, vpd2.grant_type, CASE WHEN mvdf.operator='gt' THEN 'With more than 3 classrooms ' ELSE 'With 3 classrooms or fewer ' END as classroom_count,count(distinct tse.sid), vpd2.grant_amount * count(distinct tse.sid) as total_grant from (select vdf.dise_code as dise_id, CASE WHEN vdf.classroom_count <= CAST (vpd.factor AS INT) THEN 'lt' ELSE 'gt' END as operator from vw_paisa_data vpd, vw_dise_info vdf where vpd.criteria='classroom_count') AS mvdf, tb_electedrep_master tem, tb_school_electedrep tse, vw_school_dise vsd, vw_paisa_data vpd2 where tem.id=tse.mp_const_id and tse.sid = vsd.sid and mvdf.dise_id=vsd.dise_code and mvdf.operator = vpd2.operator and tse.mp_const_id=$s group by tem.const_ward_name, vpd2.grant_type, mvdf.operator, vpd2.grant_amount order by tem.const_ward_name;",
'mp_annualgrant_sch':"select tem.const_ward_name, vsd.cat, vpd.grant_type, count(distinct tse.sid), vpd.grant_amount * count(distinct tse.sid) as total_grant from tb_electedrep_master tem, tb_school_electedrep tse, vw_school_dise vsd, vw_paisa_data vpd where tem.id=tse.mp_const_id and tse.sid=vsd.sid and vpd.criteria='school_cat' and vpd.factor = vsd.cat::text and tse.mp_const_id=$s group by tem.const_ward_name, vsd.cat,vpd.grant_type,vpd.grant_amount order by tem.const_ward_name, vsd.cat;",
'mp_neighbor_annual':"select tem.const_ward_name, vsd.cat, vpd.grant_type, vpd.grant_amount * count(distinct tse.sid) as total_grant from tb_electedrep_master tem, tb_school_electedrep tse, vw_school_dise vsd, vw_paisa_data vpd where tem.id=tse.mp_const_id and tse.sid=vsd.sid and vpd.criteria='school_cat' and vpd.factor = vsd.cat::text and tem.elec_comm_code in $s group by tem.const_ward_name, vsd.cat,vpd.grant_type,vpd.grant_amount order by tem.const_ward_name, vsd.cat;",
'mp_neighbor_tlm':"select tem.const_ward_name, vpd.grant_type, vpd.grant_amount, vpd.grant_amount* sum(vdf.teacher_count) as total_grant from tb_electedrep_master tem,tb_school_electedrep tse, vw_paisa_data vpd, vw_school_dise vsd, vw_dise_info vdf where tem.id=tse.mp_const_id and tse.sid=vsd.sid and vdf.dise_code=vsd.dise_code and vpd.criteria='teacher_count' and tem.elec_comm_code in $s group by tem.const_ward_name, vpd.grant_type, vpd.grant_amount;",
'mp_neighbor_mntnc':"select tem.const_ward_name, vpd2.grant_type, CASE WHEN mvdf.operator='gt' THEN 'With more than 3 classrooms ' ELSE 'With 3 classrooms or fewer ' END as classroom_count, vpd2.grant_amount * count(distinct tse.sid) as total_grant from (select vdf.dise_code as dise_id, CASE WHEN vdf.classroom_count <= CAST (vpd.factor AS INT) THEN 'lt' ELSE 'gt' END as operator from vw_paisa_data vpd, vw_dise_info vdf where vpd.criteria='classroom_count') AS mvdf, tb_electedrep_master tem, tb_school_electedrep tse, vw_school_dise vsd, vw_paisa_data vpd2 where tem.id=tse.mp_const_id and tse.sid = vsd.sid and mvdf.dise_id=vsd.dise_code and mvdf.operator = vpd2.operator and tem.elec_comm_code in $s group by tem.const_ward_name, vpd2.grant_type, mvdf.operator, vpd2.grant_amount order by tem.const_ward_name;",
'mp_abs_schcount':"select count(distinct tse.sid) from tb_school_electedrep tse where tse.mp_const_id=$s and tse.heirarchy=1;",
'mp_abs_preschcount':"select count(distinct tse.sid) from tb_school_electedrep tse where tse.mp_const_id=$s and tse.heirarchy=2;",
'mp_fin_schcount':"select count(distinct tse.sid) from vw_school_dise vsd, tb_school_electedrep tse where vsd.sid=tse.sid and tse.mp_const_id=$s and tse.heirarchy=1;",
'mp_ang_infra':"select distinct aia.ai_metric, count(distinct aia.sid), aia.ai_group from vw_ang_infra_agg aia, tb_school_electedrep tse where tse.sid=aia.sid and tse.mp_const_id=$s and aia.perc_score=100 group by aia.ai_metric,aia.ai_group;",
'mp_infra_count':"select count(distinct aia.sid) from vw_ang_infra_agg aia, tb_school_electedrep tse where tse.sid=aia.sid and tse.mp_const_id=$s;",
'mp_dise_facility':"select distinct dfa.df_metric, count(distinct dfa.dise_code),dfa.df_group from vw_dise_facility_agg dfa, tb_school_electedrep tse,vw_school_dise vsd where tse.sid=vsd.sid and vsd.dise_code=dfa.dise_code and tse.mp_const_id=$s and dfa.score=100 group by dfa.df_metric,dfa.df_group;",
'mp_dise_count':"select count(distinct dfa.dise_code) from vw_dise_facility_agg dfa, tb_school_electedrep tse,vw_school_dise vsd where tse.sid=vsd.sid and vsd.dise_code=dfa.dise_code and tse.mp_const_id=$s;",
'mp_lib_count':"select count(distinct li.sid) from vw_libinfra li, tb_school_electedrep tse where tse.sid=li.sid and tse.mp_const_id=$s;",
'mp_lib_status':"select li.libstatus, count(distinct li.sid) from vw_libinfra li, tb_school_electedrep tse where tse.sid=li.sid and tse.mp_const_id=$s group by li.libstatus;",
'mp_lib_summary':"select sum(numbooks) as totalbooks,sum(numracks) as totalracks,sum(numtables) as totaltables ,sum(numchairs) as totalchairs, sum(numcomputers) as totalcomps,sum(numups) as totalups from vw_libinfra li, tb_school_electedrep tse where tse.sid=li.sid and tse.mp_const_id=$s;",
'mp_neighbours_dise':"select distinct tem.const_ward_name, dfa.df_metric as a1, count(distinct dfa.dise_code),dfa.df_group as a2 from vw_dise_facility_agg dfa, tb_school_electedrep tse, tb_electedrep_master tem,vw_school_dise vsd where tse.sid=vsd.sid and vsd.dise_code=dfa.dise_code and tse.mp_const_id=tem.id and tem.elec_comm_code in $s and dfa.score=100 group by tem.const_ward_name, dfa.df_metric, dfa.df_group order by tem.const_ward_name,dfa.df_group;",
'mp_neighbours_anginfra':"select distinct tem.const_ward_name, aia.ai_metric as a1, count(distinct aia.sid), aia.ai_group as a2 from vw_ang_infra_agg aia, tb_school_electedrep tse,tb_electedrep_master tem where tse.sid=aia.sid and tse.mp_const_id=tem.id and tem.elec_comm_code in $s and aia.perc_score=100 group by tem.const_ward_name, aia.ai_metric,aia.ai_group order by tem.const_ward_name,aia.ai_group;",
'mp_neighbours_ai_count':"select tem.const_ward_name, count(distinct aia.sid) from vw_ang_infra_agg aia, tb_school_electedrep tse,tb_electedrep_master tem where tse.sid=aia.sid and tse.mp_const_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
'mp_neighbours_df_count':"select tem.const_ward_name, count(distinct dfa.dise_code) from vw_dise_facility_agg dfa, tb_school_electedrep tse,tb_electedrep_master tem,vw_school_dise vsd where tse.sid=vsd.sid and vsd.dise_code=dfa.dise_code and tse.mp_const_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
'mp_lib_lang':"select month, year, book_lang, sum(child_count) as txncount from vw_lib_lang_agg li, tb_school_electedrep tse where tse.sid=li.sid and tse.mp_const_id=$s and year='2011-2012' group by month, year, book_lang order by month, txncount desc;",
'mp_lib_level':"select month, year, book_level, sum(child_count) as txncount from vw_lib_level_agg li, tb_school_electedrep tse where tse.sid=li.sid and tse.mp_const_id=$s and year='2011-2012' group by month, year, book_level order by month, txncount desc;",
'mp_lib_class_lang':"select class as clas, book_lang, sum(child_count) as txncount from vw_lib_lang_agg li, tb_school_electedrep tse where tse.sid=li.sid and tse.mp_const_id=$s and year='2011-2012' group by class, book_lang order by class, txncount desc;",
'mp_lib_class_level':"select class as clas, book_level, sum(child_count) as txncount from vw_lib_level_agg li, tb_school_electedrep tse where tse.sid=li.sid and tse.mp_const_id=$s and year='2011-2012' group by class, book_level order by class, txncount desc;",
'mp_neighbours_libinfra':"select tem.const_ward_name, sum(li.numbooks) as count from vw_libinfra li, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=li.sid and tse.mp_const_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
'mp_neighbours_libschcount':"select tem.const_ward_name, count(distinct li.sid) as count from vw_libinfra li, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=li.sid and tse.mp_const_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
'mp_neighbours_libtxn':"select tem.const_ward_name, sum(llang.child_count) as count from vw_lib_lang_agg llang, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=llang.sid and tse.mp_const_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
'mp_neighbours_libstu':"select tem.const_ward_name, sum(tssc.numstu) as count from tb_school_stu_counts tssc, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=tssc.sid and tse.mp_const_id=tem.id and tse.heirarchy=1 and tem.elec_comm_code in $s group by tem.const_ward_name;",
'mp_sch_assess_class':"select vra.class as a1, vra.grade, sum(vra.stucount) as count from vw_reading_2011_agg vra, tb_school_electedrep tse where tse.sid=vra.sid and tse.mp_const_id=$s and vra.acyear='2011-2012' and vra.grade not in ('null','',' ') and vra.class is not null group by vra.class, vra.grade;",
'mp_sch_assess_bang':"select vra.grade, sum(vra.stucount) as count from vw_reading_2011_agg vra where vra.acyear='2011-2012' and vra.grade not in ('null','',' ') and vra.class is not null group by vra.grade;",
'mp_sch_assess_const':"select vra.grade, sum(vra.stucount) as count from vw_reading_2011_agg vra, tb_school_electedrep tse where tse.sid=vra.sid and tse.mp_const_id=$s and vra.acyear='2011-2012' and vra.grade not in ('null','',' ') and vra.class is not null group by vra.grade;",
'mp_sch_assess_gender':"select vra.gender as a1, vra.grade, sum(vra.stucount) as count from vw_reading_2011_agg vra, tb_school_electedrep tse where tse.sid=vra.sid and tse.mp_const_id=$s and vra.acyear='2011-2012' and vra.grade not in ('null','',' ') and vra.gender != 'err' group by vra.gender, vra.grade;",
'mp_sch_assess_cnt':"select count(distinct vra.sid) as schcount, sum(vra.stucount) as stucount from vw_reading_2011_agg vra, tb_school_electedrep tse where tse.sid=vra.sid and tse.mp_const_id=$s and vra.acyear='2011-2012';",
'mp_sch_assess_bang_cnt':"select count(distinct vra.sid) from vw_reading_2011_agg vra where vra.acyear='2011-2012';",
'mp_ang_assess_score':"select avg(vap.median_score * 100/ 56)::int as res from vw_angpre_2011_agg vap, tb_school_electedrep tse where tse.sid=vap.sid and tse.mp_const_id=$s;",
'mp_ang_assess_bang':"select avg(vap.median_score * 100/ 56)::int as res from vw_angpre_2011_agg vap;",
'mp_ang_assess_gender':"select vap.gender, avg(vap.median_score * 100/ 56)::int as res from vw_angpre_2011_agg vap, tb_school_electedrep tse where tse.sid=vap.sid and tse.mp_const_id=$s group by vap.gender;",
'mp_ang_assess_bang_gender':"select vap.gender, avg(vap.median_score * 100/ 56)::int as res from vw_angpre_2011_agg vap group by vap.gender;",
'mp_ang_assess_cnt':"select count(distinct vap.sid),sum(vap.stucount) from vw_angpre_2011_agg vap, tb_school_electedrep tse where tse.sid=vap.sid and tse.mp_const_id=$s;",
'mp_ang_assess_bang_cnt':"select count(distinct vap.sid) from vw_angpre_2011_agg vap;",
'mp_ang_assess_neighbor':'select tem.const_ward_name, vap.gender, avg(vap.median_score * 100/ 56)::int as res from vw_angpre_2011_agg vap, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=vap.sid and tse.mp_const_id=tem.id and tse.heirarchy=2 and tem.elec_comm_code in $s group by tem.const_ward_name,vap.gender;'
}

corporator_queries = {
'corporator_gend_sch':"select tssc.sex, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.ward_id=$s and heirarchy=1 group by tssc.sex",
'corporator_gend_presch':"select tssc.sex, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.ward_id=$s and heirarchy=2 and tssc.cat='Anganwadi' group by tssc.sex",
'corporator_mt_sch':"select tssc.mt, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.ward_id=$s and heirarchy=1 group by tssc.mt;",
'corporator_mt_presch':"select tssc.mt, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.ward_id=$s and heirarchy=2 and tssc.cat='Anganwadi' group by tssc.mt;",
'corporator_schcount':"select count(distinct tssc.sid) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.ward_id=$s and tse.heirarchy=1;",
'corporator_preschcount':"select count(distinct tssc.sid) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.ward_id=$s and tse.heirarchy=2 and tssc.sid=tse.sid and tssc.cat='Anganwadi';",
'corporator_const_details':"select elec_comm_code, const_ward_name , current_elected_rep, const_ward_type, neighbours,current_elected_party from tb_electedrep_master where const_ward_type='Ward' and id=$s;",
'corporator_moi_sch':"select distinct tssc.moi as a1, count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.ward_id=$s and heirarchy=1 group by tssc.moi;",
#'corporator_moi_presch':"select distinct tssc.moi, count(distinct tssc.sid) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.ward_id=$s and heirarchy=2 and tssc.cat='Anganwadi' group by tssc.moi;",
'corporator_cat_sch':"select distinct tssc.cat as a1, count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.ward_id=$s and heirarchy=1 group by tssc.cat;",
'corporator_cat_presch':"select distinct tssc.cat, count(distinct tssc.sid) from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.ward_id=$s and heirarchy=2 and tssc.cat='Anganwadi' group by tssc.cat;",
'corporator_neighbour_sch':"select distinct tem.const_ward_name,count(distinct tssc.sid) from tb_school_stu_counts tssc, tb_school_electedrep tse, tb_electedrep_master tem where tse.ward_id = tem.id and tse.sid=tssc.sid and tem.elec_comm_code in $s and tse.heirarchy=1 group by tem.const_ward_name;",
'corporator_neighbour_presch':"select distinct tem.const_ward_name,count(distinct tssc.sid) from tb_school_stu_counts tssc, tb_school_electedrep tse, tb_electedrep_master tem where tse.ward_id = tem.id and tse.sid=tssc.sid and tem.elec_comm_code in $s and tse.heirarchy=2 and tssc.cat='Anganwadi' group by tem.const_ward_name;",
'corporator_neighbour_gendsch':"select distinct tem.const_ward_name, tssc.sex, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse,tb_electedrep_master tem where tse.sid=tssc.sid and tse.ward_id = tem.id and tem.elec_comm_code in $s and heirarchy=1 group by tem.const_ward_name,tssc.sex",
'corporator_neighbour_gendpresch':"select distinct tem.const_ward_name, tssc.sex, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse,tb_electedrep_master tem where tse.sid=tssc.sid and tse.ward_id = tem.id and tem.elec_comm_code in $s and heirarchy=2 and tssc.cat='Anganwadi' group by tem.const_ward_name,tssc.sex",
'corporator_enrol_sch':"select distinct tssc.cat as a1, sum(tssc.numstu)/count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.ward_id=$s and heirarchy=1 group by tssc.cat;",
'corporator_enrol_presch':"select distinct tssc.cat as a1, sum(tssc.numstu)/count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.ward_id=$s and heirarchy=2 and tssc.cat='Anganwadi' group by tssc.cat;",
'corporator_tlmgrant_sch':"select tem.const_ward_name, vpd.grant_type, vpd.grant_amount, vpd.grant_amount* sum(vdf.teacher_count) as total_grant from tb_electedrep_master tem,tb_school_electedrep tse, vw_paisa_data vpd, vw_school_dise vsd, vw_dise_info vdf where tem.id=tse.ward_id and tse.sid=vsd.sid and vdf.dise_code=vsd.dise_code and vpd.criteria='teacher_count' and tse.ward_id=$s group by tem.const_ward_name, vpd.grant_type, vpd.grant_amount;",
'corporator_mtncgrant_sch':"select tem.const_ward_name, vpd2.grant_type, CASE WHEN mvdf.operator='gt' THEN 'With more than 3 classrooms ' ELSE 'With 3 classrooms or fewer ' END as classroom_count, count(distinct tse.sid), vpd2.grant_amount * count(distinct tse.sid) as total_grant from (select vdf.dise_code as dise_id, CASE WHEN vdf.classroom_count <= CAST (vpd.factor AS INT) THEN 'lt' ELSE 'gt' END as operator from vw_paisa_data vpd, vw_dise_info vdf where vpd.criteria='classroom_count') AS mvdf, tb_electedrep_master tem, tb_school_electedrep tse, vw_school_dise vsd, vw_paisa_data vpd2 where tem.id=tse.ward_id and tse.sid = vsd.sid and mvdf.dise_id=vsd.dise_code and mvdf.operator = vpd2.operator and tse.ward_id=$s group by tem.const_ward_name, vpd2.grant_type, mvdf.operator, vpd2.grant_amount order by tem.const_ward_name;",
'corporator_annualgrant_sch':"select tem.const_ward_name, vsd.cat, vpd.grant_type, count(distinct tse.sid), vpd.grant_amount * count(distinct tse.sid) as total_grant from tb_electedrep_master tem, tb_school_electedrep tse, vw_school_dise vsd, vw_paisa_data vpd where tem.id=tse.ward_id and tse.sid=vsd.sid and vpd.criteria='school_cat' and vpd.factor = vsd.cat::text and tse.ward_id=$s group by tem.const_ward_name, vsd.cat,vpd.grant_type,vpd.grant_amount order by tem.const_ward_name, vsd.cat;",
'corporator_neighbor_annual':"select tem.const_ward_name, vsd.cat, vpd.grant_type, vpd.grant_amount * count(distinct tse.sid) as total_grant from tb_electedrep_master tem, tb_school_electedrep tse, vw_school_dise vsd, vw_paisa_data vpd where tem.id=tse.ward_id and tse.sid=vsd.sid and vpd.criteria='school_cat' and vpd.factor = vsd.cat::text and tem.elec_comm_code in $s group by tem.const_ward_name, vsd.cat,vpd.grant_type,vpd.grant_amount order by tem.const_ward_name, vsd.cat;",
'corporator_neighbor_tlm':"select tem.const_ward_name, vpd.grant_type, vpd.grant_amount, vpd.grant_amount* sum(vdf.teacher_count) as total_grant from tb_electedrep_master tem,tb_school_electedrep tse, vw_paisa_data vpd, vw_school_dise vsd, vw_dise_info vdf where tem.id=tse.ward_id and tse.sid=vsd.sid and vdf.dise_code=vsd.dise_code and vpd.criteria='teacher_count' and tem.elec_comm_code in $s group by tem.const_ward_name, vpd.grant_type, vpd.grant_amount;",
'corporator_neighbor_mntnc':"select tem.const_ward_name, vpd2.grant_type, CASE WHEN mvdf.operator='gt' THEN 'With more than 3 classrooms ' ELSE 'With 3 classrooms or fewer ' END as classroom_count, vpd2.grant_amount * count(distinct tse.sid) as total_grant from (select vdf.dise_code as dise_id, CASE WHEN vdf.classroom_count <= CAST (vpd.factor AS INT) THEN 'lt' ELSE 'gt' END as operator from vw_paisa_data vpd, vw_dise_info vdf where vpd.criteria='classroom_count') AS mvdf, tb_electedrep_master tem, tb_school_electedrep tse, vw_school_dise vsd, vw_paisa_data vpd2 where tem.id=tse.ward_id and tse.sid = vsd.sid and mvdf.dise_id=vsd.dise_code and mvdf.operator = vpd2.operator and tem.elec_comm_code in $s group by tem.const_ward_name, vpd2.grant_type, mvdf.operator, vpd2.grant_amount order by tem.const_ward_name;",
'corporator_abs_schcount':"select count(distinct tse.sid) from tb_school_electedrep tse where tse.ward_id=$s and tse.heirarchy=1;",
'corporator_abs_preschcount':"select count(distinct tse.sid) from tb_school_electedrep tse where tse.ward_id=$s and tse.heirarchy=2;",
'corporator_fin_schcount':"select count(distinct tse.sid) from vw_school_dise vsd, tb_school_electedrep tse where vsd.sid=tse.sid and tse.ward_id=$s and tse.heirarchy=1;",
'corporator_ang_infra':"select distinct aia.ai_metric, count(distinct aia.sid),aia.ai_group from vw_ang_infra_agg aia, tb_school_electedrep tse where tse.sid=aia.sid and tse.ward_id=$s and aia.perc_score=100 group by aia.ai_metric,aia.ai_group;",
'corporator_infra_count':"select count(distinct aia.sid) from vw_ang_infra_agg aia, tb_school_electedrep tse where tse.sid=aia.sid and tse.ward_id=$s;",
'corporator_dise_facility':"select distinct dfa.df_metric, count(distinct dfa.dise_code),dfa.df_group from vw_dise_facility_agg dfa, tb_school_electedrep tse,vw_school_dise vsd where tse.sid=vsd.sid and vsd.dise_code=dfa.dise_code and tse.ward_id=$s and dfa.score=100 group by dfa.df_metric,dfa.df_group;",
'corporator_dise_count':"select count(distinct dfa.dise_code) from vw_dise_facility_agg dfa, tb_school_electedrep tse,vw_school_dise vsd where tse.sid=vsd.sid and vsd.dise_code=dfa.dise_code and tse.ward_id=$s;",
'corporator_lib_count':"select count(distinct li.sid) from vw_libinfra li, tb_school_electedrep tse where tse.sid=li.sid and tse.ward_id=$s;",
'corporator_lib_status':"select li.libstatus, count(distinct li.sid) from vw_libinfra li, tb_school_electedrep tse where tse.sid=li.sid and tse.ward_id=$s group by li.libstatus;",
'corporator_lib_summary':"select sum(numbooks) as totalbooks,sum(numracks) as totalracks,sum(numtables) as totaltables ,sum(numchairs) as totalchairs, sum(numcomputers) as totalcomps,sum(numups) as totalups from vw_libinfra li, tb_school_electedrep tse where tse.sid=li.sid and tse.ward_id=$s;",
'corporator_neighbours_dise':"select distinct tem.const_ward_name, dfa.df_metric as a1, count(distinct dfa.dise_code),dfa.df_group as a2 from vw_dise_facility_agg dfa, tb_school_electedrep tse, tb_electedrep_master tem,vw_school_dise vsd where tse.sid=vsd.sid and vsd.dise_code=dfa.dise_code and tse.ward_id=tem.id and tem.elec_comm_code in $s and dfa.score=100 group by tem.const_ward_name, dfa.df_metric, dfa.df_group order by tem.const_ward_name,dfa.df_group;",
'corporator_neighbours_anginfra':"select distinct tem.const_ward_name, aia.ai_metric as a1, count(distinct aia.sid), aia.ai_group as a2 from vw_ang_infra_agg aia, tb_school_electedrep tse,tb_electedrep_master tem where tse.sid=aia.sid and tse.ward_id=tem.id and tem.elec_comm_code in $s and aia.perc_score=100 group by tem.const_ward_name, aia.ai_metric,aia.ai_group order by tem.const_ward_name,aia.ai_group;",
'corporator_neighbours_ai_count':"select tem.const_ward_name, count(distinct aia.sid) from vw_ang_infra_agg aia, tb_school_electedrep tse,tb_electedrep_master tem where tse.sid=aia.sid and tse.ward_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
'corporator_neighbours_df_count':"select tem.const_ward_name, count(distinct dfa.dise_code) from vw_dise_facility_agg dfa, tb_school_electedrep tse,tb_electedrep_master tem,vw_school_dise vsd where tse.sid=vsd.sid and vsd.dise_code=dfa.dise_code and tse.ward_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
'corporator_lib_lang':"select month, year, book_lang, sum(child_count) as txncount from vw_lib_lang_agg li, tb_school_electedrep tse where tse.sid=li.sid and tse.ward_id=$s and year='2011-2012' group by month, year, book_lang order by month, txncount desc;",
'corporator_lib_level':"select month, year, book_level, sum(child_count) as txncount from vw_lib_level_agg li, tb_school_electedrep tse where tse.sid=li.sid and tse.ward_id=$s and year='2011-2012' group by month, year, book_level order by month, txncount desc;",
'corporator_lib_class_lang':"select class as clas, book_lang, sum(child_count) as txncount from vw_lib_lang_agg li, tb_school_electedrep tse where tse.sid=li.sid and tse.ward_id=$s and year='2011-2012' group by class, book_lang order by class, txncount desc;",
'corporator_lib_class_level':"select class as clas, book_level, sum(child_count) as txncount from vw_lib_level_agg li, tb_school_electedrep tse where tse.sid=li.sid and tse.ward_id=$s and year='2011-2012' group by class, book_level order by class, txncount desc;",
'corporator_neighbours_libinfra':"select tem.const_ward_name, sum(li.numbooks) as count from vw_libinfra li, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=li.sid and tse.ward_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
'corporator_neighbours_libschcount':"select tem.const_ward_name, count(distinct li.sid) as count from vw_libinfra li, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=li.sid and tse.ward_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
'corporator_neighbours_libtxn':"select tem.const_ward_name, sum(llang.child_count) as count from vw_lib_lang_agg llang, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=llang.sid and tse.ward_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
'corporator_neighbours_libstu':"select tem.const_ward_name, sum(tssc.numstu) as count from tb_school_stu_counts tssc, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=tssc.sid and tse.ward_id=tem.id and tse.heirarchy=1 and tem.elec_comm_code in $s group by tem.const_ward_name;"
}

cluster_queries = {
'cluster_mdm_agg':"select mon,wk,sum(indent) as indent,sum(attend) as attend, sd.clust as name from vw_school_dise sd, vw_mdm_agg mdm where mdm.id=sd.sid and sd.clst_id=$s group by mon,wk,clust order by mon,wk;",
'cluster_klp_enrol':"select sum(case when sex='Boy' then tssc.numstu end) as num_boys,sum(case when sex='Girl' then tssc.numstu end) as num_girls from vw_school_dise sd, tb_school_stu_counts tssc where tssc.sid=sd.sid and sd.clst_id=$s and sd.sid in (select distinct id from vw_mdm_agg);",
'cluster_dise_enrol':"select sum(boys_count) as num_boys,sum(girls_count) as num_girls from vw_school_dise sd,vw_dise_info vdi where vdi.dise_code=sd.dise_code and sd.clst_id=$s and sd.sid in (select distinct id from vw_mdm_agg);",
'cluster_sch_count':"select count(distinct sd.sid) as a1,count(distinct mdm.id) as a2 from vw_school_dise sd left join vw_mdm_agg mdm on mdm.id=sd.sid where sd.clst_id=$s;"
}

block_queries = {
'block_mdm_agg':"select mon,wk,sum(indent) as indent,sum(attend) as attend, sd.block as name from vw_school_dise sd, vw_mdm_agg mdm where mdm.id=sd.sid and sd.blck_id=$s group by mon,wk,block order by mon,wk;",
'block_klp_enrol':"select sum(case when sex='Boy' then tssc.numstu end) as num_boys,sum(case when sex='Girl' then tssc.numstu end) as num_girls from vw_school_dise sd, tb_school_stu_counts tssc where tssc.sid=sd.sid and sd.blck_id=$s and sd.sid in (select distinct id from vw_mdm_agg);",
'block_dise_enrol':"select sum(boys_count) as num_boys,sum(girls_count) as num_girls from vw_school_dise sd,vw_dise_info vdi where vdi.dise_code=sd.dise_code and sd.blck_id=$s and sd.sid in (select distinct id from vw_mdm_agg);",
'block_sch_count':"select count(distinct sd.sid) as a1,count(distinct mdm.id) as a2 from vw_school_dise sd left join vw_mdm_agg mdm on mdm.id=sd.sid where sd.blck_id=$s;"
}

boundary_queries = {
'boundary_gend_sch':"select tssc.sex, sum(tssc.numstu) from tb_school_stu_counts tssc, vw_school_dise tse where tse.sid=tssc.sid and (tse.dist_id=$s or tse.blck_id=$s or tse.clst_id=$s) and type=1 group by tssc.sex",
'boundary_gend_presch':"select tssc.sex, sum(tssc.numstu) from tb_school_stu_counts tssc, vw_school_dise tse where tse.sid=tssc.sid and (tse.dist_id=$s or tse.blck_id=$s or tse.clst_id=$s) and type=2 and tssc.cat='Anganwadi' group by tssc.sex",
'boundary_mt_sch':"select tssc.mt, sum(tssc.numstu) from tb_school_stu_counts tssc, vw_school_dise tse where tse.sid=tssc.sid and (tse.dist_id=$s or tse.blck_id=$s or tse.clst_id=$s) and type=1 group by tssc.mt;",
'boundary_mt_presch':"select tssc.mt, sum(tssc.numstu) from tb_school_stu_counts tssc, vw_school_dise tse where tse.sid=tssc.sid and (tse.dist_id=$s or tse.blck_id=$s or tse.clst_id=$s) and type=2 and tssc.cat='Anganwadi' group by tssc.mt;",
'boundary_schcount':"select count(distinct tssc.sid) from tb_school_stu_counts tssc, vw_school_dise tse where tse.sid=tssc.sid and (tse.dist_id=$s or tse.blck_id=$s or tse.clst_id=$s) and tse.type=1;",
'boundary_preschcount':"select count(distinct tssc.sid) from tb_school_stu_counts tssc, vw_school_dise tse where tse.sid=tssc.sid and (tse.dist_id=$s or tse.blck_id=$s or tse.clst_id=$s) and tse.type=2 and tssc.sid=tse.sid and tssc.cat='Anganwadi';",

#'boundary_const_details':"select elec_comm_code, const_ward_name , current_elected_rep, const_ward_type, neighbours,current_elected_party from tb_electedrep_master where const_ward_type='MLA Constituency' and id=75;",

'boundary_const_details':"select distinct dist_id, district, blck_id, block, clst_id, clust, type from vw_school_dise where (dist_id=$s or blck_id=$s or clst_id=$s) limit 1;",

'boundary_moi_sch':"select distinct tssc.moi as a1, count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, vw_school_dise tse where tse.sid=tssc.sid and (tse.dist_id=$s or tse.blck_id=$s or tse.clst_id=$s) and type=1 group by tssc.moi;",
#'boundary_moi_presch':"select distinct tssc.moi as a1, count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, tb_school_electedrep tse where tse.sid=tssc.sid and tse.boundary_const_id=$s and heirarchy=2 and tssc.cat='Anganwadi' group by tssc.moi;",
'boundary_cat_sch':"select distinct tssc.cat as a1, count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, vw_school_dise tse where tse.sid=tssc.sid and (tse.dist_id=$s or tse.blck_id=$s or tse.clst_id=$s) and type=1 group by tssc.cat;",
'boundary_cat_presch':"select distinct tssc.cat as a1, count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, vw_school_dise tse where tse.sid=tssc.sid and (tse.dist_id=$s or tse.blck_id=$s or tse.clst_id=$s) and type=2 and tssc.cat='Anganwadi' group by tssc.cat;",

#'boundary_neighbour_sch':"select distinct tem.const_ward_name,count(distinct tssc.sid) from tb_school_stu_counts tssc, tb_school_electedrep tse, tb_electedrep_master tem where tse.boundary_const_id = tem.id and tse.sid=tssc.sid and tem.elec_comm_code in $s and tse.heirarchy=1 group by tem.const_ward_name;",

#'boundary_neighbour_presch':"select distinct tem.const_ward_name,count(distinct tssc.sid) from tb_school_stu_counts tssc, tb_school_electedrep tse, tb_electedrep_master tem where tse.boundary_const_id = tem.id and tse.sid=tssc.sid and tem.elec_comm_code in $s and tse.heirarchy=2 and tssc.cat='Anganwadi' group by tem.const_ward_name;",

#'boundary_neighbour_gendsch':"select distinct tem.const_ward_name, tssc.sex, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse,tb_electedrep_master tem where tse.sid=tssc.sid and tse.boundary_const_id = tem.id and tem.elec_comm_code in $s and heirarchy=1 group by tem.const_ward_name,tssc.sex",-

#'boundary_neighbour_gendpresch':"select distinct tem.const_ward_name, tssc.sex, sum(tssc.numstu) from tb_school_stu_counts tssc, tb_school_electedrep tse,tb_electedrep_master tem where tse.sid=tssc.sid and tse.boundary_const_id = tem.id and tem.elec_comm_code in $s and heirarchy=2 and tssc.cat='Anganwadi' group by tem.const_ward_name,tssc.sex",

'boundary_enrol_sch':"select distinct tssc.cat as a1, sum(tssc.numstu)/count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, vw_school_dise tse where tse.sid=tssc.sid and (tse.dist_id=$s or tse.blck_id=$s or tse.clst_id=$s) and type=1 group by tssc.cat;",
'boundary_enrol_presch':"select distinct tssc.cat as a1, sum(tssc.numstu)/count(distinct tssc.sid) as a2 from tb_school_stu_counts tssc, vw_school_dise tse where tse.sid=tssc.sid and (tse.dist_id=$s or tse.blck_id=$s or tse.clst_id=$s) and type=2 and tssc.cat='Anganwadi' group by tssc.cat;",
'boundary_tlmgrant_sch':"select vpd.grant_type, vpd.grant_amount, vpd.grant_amount* sum(vdf.teacher_count) as total_grant from vw_paisa_data vpd, vw_school_dise vsd, vw_dise_info vdf where vdf.dise_code=vsd.dise_code and vpd.criteria='teacher_count' and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s) group by vpd.grant_type, vpd.grant_amount;",
'boundary_mtncgrant_sch':"select vpd2.grant_type, CASE WHEN mvdf.operator='gt' THEN 'With more than 3 classrooms ' ELSE 'With 3 classrooms or fewer ' END as classroom_count, count(distinct vsd.sid), vpd2.grant_amount * count(distinct vsd.sid) as total_grant from (select vdf.dise_code as dise_id, CASE WHEN vdf.classroom_count <= CAST (vpd.factor AS INT) THEN 'lt' ELSE 'gt' END as operator from vw_paisa_data vpd, vw_dise_info vdf where vpd.criteria='classroom_count') AS mvdf, tb_electedrep_master tem, vw_school_dise vsd, vw_paisa_data vpd2 where mvdf.dise_id=vsd.dise_code and mvdf.operator = vpd2.operator and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s) group by vpd2.grant_type, mvdf.operator, vpd2.grant_amount;",
'boundary_annualgrant_sch':"select vsd.cat, vpd.grant_type, count(distinct vsd.sid), vpd.grant_amount * count(distinct vsd.sid) as total_grant from vw_school_dise vsd, vw_paisa_data vpd where vpd.criteria='school_cat' and vpd.factor = vsd.cat::text and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s) group by vsd.cat,vpd.grant_type,vpd.grant_amount order by vsd.cat;",

#'boundary_neighbor_annual':"select tem.const_ward_name, vsd.cat, vpd.grant_type, vpd.grant_amount * count(distinct tse.sid) as total_grant from tb_electedrep_master tem, tb_school_electedrep tse, vw_school_dise vsd, vw_paisa_data vpd where tem.id=tse.boundary_const_id and tse.sid=vsd.sid and vpd.criteria='school_cat' and vpd.factor = vsd.cat::text and tem.elec_comm_code in $s group by tem.const_ward_name, vsd.cat,vpd.grant_type,vpd.grant_amount order by tem.const_ward_name, vsd.cat;",

#'boundary_neighbor_tlm':"select tem.const_ward_name, vpd.grant_type, vpd.grant_amount, vpd.grant_amount* sum(vdf.teacher_count) as total_grant from tb_electedrep_master tem,tb_school_electedrep tse, vw_paisa_data vpd, vw_school_dise vsd, vw_dise_info vdf where tem.id=tse.boundary_const_id and tse.sid=vsd.sid and vdf.dise_code=vsd.dise_code and vpd.criteria='teacher_count' and tem.elec_comm_code in $s group by tem.const_ward_name, vpd.grant_type, vpd.grant_amount;",

#'boundary_neighbor_mntnc':"select tem.const_ward_name, vpd2.grant_type, CASE WHEN mvdf.operator='gt' THEN 'With more than 3 classrooms ' ELSE 'With 3 classrooms or fewer ' END as classroom_count, vpd2.grant_amount * count(distinct tse.sid) as total_grant from (select vdf.dise_code as dise_id, CASE WHEN vdf.classroom_count <= CAST (vpd.factor AS INT) THEN 'lt' ELSE 'gt' END as operator from vw_paisa_data vpd, vw_dise_info vdf where vpd.criteria='classroom_count') AS mvdf, tb_electedrep_master tem, tb_school_electedrep tse, vw_school_dise vsd, vw_paisa_data vpd2 where tem.id=tse.boundary_const_id and tse.sid = vsd.sid and mvdf.dise_id=vsd.dise_code and mvdf.operator = vpd2.operator and tem.elec_comm_code in $s group by tem.const_ward_name, vpd2.grant_type, mvdf.operator, vpd2.grant_amount order by tem.const_ward_name;",

'boundary_abs_schcount':"select count(distinct vsd.sid) from vw_school_dise vsd where (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s) and vsd.type=1;",
'boundary_abs_preschcount':"select count(distinct vsd.sid) from vw_school_dise vsd where (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s) and vsd.type=2;",
'boundary_fin_schcount':"select count(distinct vsd.sid) from vw_school_dise vsd where (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s) and vsd.type=1;",
'boundary_ang_infra':"select distinct aia.ai_metric, count(distinct aia.sid),aia.ai_group from vw_ang_infra_agg aia, vw_school_dise vsd where vsd.sid=aia.sid and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s) and aia.perc_score=100 group by aia.ai_metric,aia.ai_group;",
'boundary_infra_count':"select count(distinct aia.sid) from vw_ang_infra_agg aia, vw_school_dise vsd where vsd.sid=aia.sid and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s);",
'boundary_dise_facility':"select distinct dfa.df_metric, count(distinct dfa.dise_code),dfa.df_group from vw_dise_facility_agg dfa, vw_school_dise vsd where vsd.dise_code=dfa.dise_code and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s) and dfa.score=100 group by dfa.df_metric,dfa.df_group;",
'boundary_dise_count':"select count(distinct dfa.dise_code) from vw_dise_facility_agg dfa, vw_school_dise vsd where vsd.dise_code=dfa.dise_code and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s);",
'boundary_lib_count':"select count(distinct li.sid) from vw_libinfra li, vw_school_dise vsd where vsd.sid=li.sid and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s);",
'boundary_lib_status':"select li.libstatus, count(distinct li.sid) from vw_libinfra li, vw_school_dise vsd where vsd.sid=li.sid and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s) group by li.libstatus;",
'boundary_lib_summary':"select sum(numbooks) as totalbooks,sum(numracks) as totalracks,sum(numtables) as totaltables ,sum(numchairs) as totalchairs, sum(numcomputers) as totalcomps,sum(numups) as totalups from vw_libinfra li, vw_school_dise vsd where vsd.sid=li.sid and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s);",

#'boundary_neighbours_dise':"select distinct tem.const_ward_name, dfa.df_metric as a1, count(distinct dfa.dise_code),dfa.df_group as a2 from vw_dise_facility_agg dfa, tb_school_electedrep tse, tb_electedrep_master tem,vw_school_dise vsd where tse.sid=vsd.sid and vsd.dise_code=dfa.dise_code and tse.boundary_const_id=tem.id and tem.elec_comm_code in $s and dfa.score=100 group by tem.const_ward_name, dfa.df_metric, dfa.df_group order by tem.const_ward_name,dfa.df_group;",
#'boundary_neighbours_anginfra':"select distinct tem.const_ward_name, aia.ai_metric as a1, count(distinct aia.sid), aia.ai_group as a2 from vw_ang_infra_agg aia, tb_school_electedrep tse,tb_electedrep_master tem where tse.sid=aia.sid and tse.boundary_const_id=tem.id and tem.elec_comm_code in $s and aia.perc_score=100 group by tem.const_ward_name, aia.ai_metric,aia.ai_group order by tem.const_ward_name,aia.ai_group;",
#'boundary_neighbours_ai_count':"select tem.const_ward_name, count(distinct aia.sid) from vw_ang_infra_agg aia, tb_school_electedrep tse,tb_electedrep_master tem where tse.sid=aia.sid and tse.boundary_const_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
#'boundary_neighbours_df_count':"select tem.const_ward_name, count(distinct dfa.dise_code) from vw_dise_facility_agg dfa, tb_school_electedrep tse,tb_electedrep_master tem,vw_school_dise vsd where tse.sid=vsd.sid and vsd.dise_code=dfa.dise_code and tse.boundary_const_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
'boundary_lib_lang':"select month, year, book_lang, sum(child_count) as txncount from vw_lib_lang_agg li, vw_school_dise vsd where vsd.sid=li.sid and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s) and year='2011-2012' group by month, year, book_lang order by month, txncount desc;",
'boundary_lib_level':"select month, year, book_level, sum(child_count) as txncount from vw_lib_level_agg li, vw_school_dise vsd where vsd.sid=li.sid and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s) and year='2011-2012' group by month, year, book_level order by month, txncount desc;",
'boundary_lib_class_lang':"select class as clas, book_lang, sum(child_count) as txncount from vw_lib_lang_agg li, vw_school_dise vsd where vsd.sid=li.sid and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s) and year='2011-2012' group by class, book_lang order by class, txncount desc;",
'boundary_lib_class_level':"select class as clas, book_level, sum(child_count) as txncount from vw_lib_level_agg li, vw_school_dise vsd where vsd.sid=li.sid and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s) and year='2011-2012' group by class, book_level order by class, txncount desc;",

#'boundary_neighbours_libinfra':"select tem.const_ward_name, sum(li.numbooks) as count from vw_libinfra li, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=li.sid and tse.boundary_const_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
#'boundary_neighbours_libschcount':"select tem.const_ward_name, count(distinct li.sid) as count from vw_libinfra li, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=li.sid and tse.boundary_const_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
#'boundary_neighbours_libtxn':"select tem.const_ward_name, sum(llang.child_count) as count from vw_lib_lang_agg llang, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=llang.sid and tse.boundary_const_id=tem.id and tem.elec_comm_code in $s group by tem.const_ward_name;",
#'boundary_neighbours_libstu':"select tem.const_ward_name, sum(tssc.numstu) as count from tb_school_stu_counts tssc, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=tssc.sid and tse.boundary_const_id=tem.id and tse.heirarchy=1 and tem.elec_comm_code in $s group by tem.const_ward_name;",
'boundary_sch_assess_class':"select vra.class as a1, vra.grade, sum(vra.stucount) as count from vw_reading_2011_agg vra, vw_school_dise vsd where vsd.sid=vra.sid and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s) and vra.acyear='2011-2012' and vra.grade not in ('null','',' ') and vra.class is not null group by vra.class, vra.grade;",

'boundary_sch_assess_bang':"select vra.grade, sum(vra.stucount) as count from vw_reading_2011_agg vra where vra.acyear='2011-2012' and vra.grade not in ('null','',' ') and vra.class is not null group by vra.grade;",

'boundary_sch_assess_const':"select vra.grade, sum(vra.stucount) as count from vw_reading_2011_agg vra, vw_school_dise vsd where vsd.sid=vra.sid and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s) and vra.acyear='2011-2012' and vra.grade not in ('null','',' ') and vra.class is not null group by vra.grade;",
'boundary_sch_assess_gender':"select vra.gender as a1, vra.grade, sum(vra.stucount) as count from vw_reading_2011_agg vra, vw_school_dise vsd where vsd.sid=vra.sid and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s) and vra.acyear='2011-2012' and vra.grade not in ('null','',' ') and vra.gender != 'err' group by vra.gender, vra.grade;",
'boundary_sch_assess_cnt':"select count(distinct vra.sid) as schcount, sum(vra.stucount) as stucount from vw_reading_2011_agg vra, vw_school_dise vsd where vsd.sid=vra.sid and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s) and vra.acyear='2011-2012';",

'boundary_sch_assess_bang_cnt':"select count(distinct vra.sid) from vw_reading_2011_agg vra where vra.acyear='2011-2012';",

'boundary_ang_assess_score':"select avg(vap.median_score * 100/ 56)::int as res from vw_angpre_2011_agg vap, vw_school_dise vsd where vsd.sid=vap.sid and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s);",

'boundary_ang_assess_bang':"select avg(vap.median_score * 100/ 56)::int as res from vw_angpre_2011_agg vap;",

'boundary_ang_assess_gender':"select vap.gender, avg(vap.median_score * 100/ 56)::int as res from vw_angpre_2011_agg vap, vw_school_dise vsd where vsd.sid=vap.sid and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s) group by vap.gender;",

'boundary_ang_assess_bang_gender':"select vap.gender, avg(vap.median_score * 100/ 56)::int as res from vw_angpre_2011_agg vap group by vap.gender;",

'boundary_ang_assess_cnt':"select count(distinct vap.sid),sum(vap.stucount) from vw_angpre_2011_agg vap, vw_school_dise vsd where vsd.sid=vap.sid and (vsd.dist_id=$s or vsd.blck_id=$s or vsd.clst_id=$s);",

'boundary_ang_assess_bang_cnt':"select count(distinct vap.sid) from vw_angpre_2011_agg vap;",

#'boundary_ang_assess_neighbor':'select tem.const_ward_name, vap.gender, avg(vap.median_score * 100/ 56)::int as res from vw_angpre_2011_agg vap, tb_school_electedrep tse, tb_electedrep_master tem where tse.sid=vap.sid and tse.boundary_const_id=tem.id and tse.heirarchy=2 and tem.elec_comm_code in $s group by tem.const_ward_name,vap.gender;'
}


def getDictionary(constype = 'common'):
  if constype == 'mp':
    return mp_queries
  elif constype == 'mla':
    return mla_queries
  elif constype == 'corporator':
    return corporator_queries
  elif constype == 'cluster':
    return cluster_queries
  elif constype == 'block':
    return block_queries
  elif constype == 'boundary':
    return boundary_queries
  else:
    return common_queries
