phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/75/english/learning	/home/megha/www/reports/learning/English/MLA_Anekal.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/76/english/learning	/home/megha/www/reports/learning/English/MLA_Hoskote.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/208/english/learning	/home/megha/www/reports/learning/English/MLA_Yelahanka.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/209/english/learning	/home/megha/www/reports/learning/English/MLA_Rajajinagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/210/english/learning	/home/megha/www/reports/learning/English/MLA_Chickpet.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/211/english/learning	/home/megha/www/reports/learning/English/MLA_Chamarajpet.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/212/english/learning	/home/megha/www/reports/learning/English/MLA_Malleshwaram.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/215/english/learning	/home/megha/www/reports/learning/English/MLA_Shivajinagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/216/english/learning	/home/megha/www/reports/learning/English/MLA_Basavanagudi.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/217/english/learning	/home/megha/www/reports/learning/English/MLA_Gandhinagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/218/english/learning	/home/megha/www/reports/learning/English/MLA_Shantinagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/219/english/learning	/home/megha/www/reports/learning/English/MLA_Jayanagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/246/english/learning	/home/megha/www/reports/learning/English/MLA_KR_Puram.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/247/english/learning	/home/megha/www/reports/learning/English/MLA_Rajarajeshwarinagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/248/english/learning	/home/megha/www/reports/learning/English/MLA_Dasarahalli.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/249/english/learning	/home/megha/www/reports/learning/English/MLA_Mahalakshmi_Layout.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/250/english/learning	/home/megha/www/reports/learning/English/MLA_Hebbal.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/251/english/learning	/home/megha/www/reports/learning/English/MLA_Pulakeshinagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/252/english/learning	/home/megha/www/reports/learning/English/MLA_Sarvajna_Nagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/253/english/learning	/home/megha/www/reports/learning/English/MLA_CV_Raman_Nagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/254/english/learning	/home/megha/www/reports/learning/English/MLA_Govindrajnagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/255/english/learning	/home/megha/www/reports/learning/English/MLA_Vijayanagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/256/english/learning	/home/megha/www/reports/learning/English/MLA_Padmanabhanagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/257/english/learning	/home/megha/www/reports/learning/English/MLA_BTM_Layout.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/258/english/learning	/home/megha/www/reports/learning/English/MLA_Mahadevpura.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/259/english/learning	/home/megha/www/reports/learning/English/MLA_Bommanahalli.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/260/english/learning	/home/megha/www/reports/learning/English/MLA_Bangalore_South.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/261/english/learning	/home/megha/www/reports/learning/English/MLA_Byatrayanapura.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/262/english/learning	/home/megha/www/reports/learning/English/MLA_Yashwantpura.pdf
echo “ MLA English done”				
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mp/227/english/learning	/home/megha/www/reports/learning/English/MP_Chikkaballapur.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mp/238/english/learning	/home/megha/www/reports/learning/English/MP_Bangalore_North.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mp/245/english/learning	/home/megha/www/reports/learning/English/MP_Bangalore_South.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mp/263/english/learning	/home/megha/www/reports/learning/English/MP_Bangalore_Rural.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mp/264/english/learning	/home/megha/www/reports/learning/English/MP_Bangalore_Central.pdf
echo “ MP English done”				
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/75/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Anekal.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/76/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Hoskote.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/208/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Yelahanka.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/209/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Rajajinagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/210/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Chickpet.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/211/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Chamarajpet.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/212/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Malleshwaram.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/215/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Shivajinagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/216/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Basavanagudi.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/217/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Gandhinagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/218/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Shantinagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/219/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Jayanagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/246/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_KR_Puram.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/247/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Rajarajeshwarinagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/248/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Dasarahalli.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/249/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Mahalakshmi_Layout.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/250/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Hebbal.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/251/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Pulakeshinagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/252/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Sarvajna_Nagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/253/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_CV_Raman_Nagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/254/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Govindrajnagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/255/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Vijayanagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/256/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Padmanabhanagar.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/257/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_BTM_Layout.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/258/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Mahadevpura.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/259/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Bommanahalli.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/260/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Bangalore_South.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/261/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Byatrayanapura.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mla/262/kannada/learning /home/megha/www/reports/learning/Kannada/MLA_Yashwantpura.pdf
echo “ MLA Kannada done”    
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mp/227/kannada/learning /home/megha/www/reports/learning/Kannada/MP_Chikkaballapur.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mp/238/kannada/learning /home/megha/www/reports/learning/Kannada/MP_Bangalore_North.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mp/245/kannada/learning /home/megha/www/reports/learning/Kannada/MP_Bangalore_South.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mp/263/kannada/learning /home/megha/www/reports/learning/Kannada/MP_Bangalore_Rural.pdf
phantomjs /home/megha/lib/phantomjs/myscripts/w2i.js http://dev.klp.org.in:8013/charts/mp/264/kannada/learning /home/megha/www/reports/learning/Kannada/MP_Bangalore_Central.pdf
echo “ MP Kannada done”    
