#CLUSTER%20%20%20%20
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/domlur/2/5 /home/megha/nutrition_ap/cluster/domlur.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/hunasamaranahalli/2/5 /home/megha/nutrition_ap/cluster/hunasamaranahalli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/kodigehalli/2/5 /home/megha/nutrition_ap/cluster/kodigehalli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/sriramapura/2/5 /home/megha/nutrition_ap/cluster/sriramapura.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/frazer%20town/2/5 /home/megha/nutrition_ap/cluster/frazer_town.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/jodi%20huskur/2/5 /home/megha/nutrition_ap/cluster/jodi_huskur.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/madivala/2/5 /home/megha/nutrition_ap/cluster/madivala.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/chikkajala/2/5 /home/megha/nutrition_ap/cluster/chikkajala.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/vasanthnagar/2/5 /home/megha/nutrition_ap/cluster/vasanthnagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/veerabadra%20nagara/2/5 /home/megha/nutrition_ap/cluster/veerabadra_nagara.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/chikkabidarakallu/2/5 /home/megha/nutrition_ap/cluster/chikkabidarakallu.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/hosakerehalli/2/5 /home/megha/nutrition_ap/cluster/hosakerehalli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/ullalupanagara/2/5 /home/megha/nutrition_ap/cluster/ullalupanagara.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/uttara%20halli/2/5 /home/megha/nutrition_ap/cluster/uttara_halli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/beratena%20agrahara/2/5 /home/megha/nutrition_ap/cluster/beratena_agrahara.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/thanisandra/2/5 /home/megha/nutrition_ap/cluster/thanisandra.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/varanasi/2/5 /home/megha/nutrition_ap/cluster/varanasi.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/j%20c%20nagar/2/5 /home/megha/nutrition_ap/cluster/j_c_nagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/k%20r%20puram/2/5 /home/megha/nutrition_ap/cluster/k_r_puram.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/yelehanka%20new%20town/2/5 /home/megha/nutrition_ap/cluster/yelehanka_new_town.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/vajara%20halli/2/5 /home/megha/nutrition_ap/cluster/vajara_halli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/rammurthynagar/2/5 /home/megha/nutrition_ap/cluster/rammurthynagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/channasandra/2/5 /home/megha/nutrition_ap/cluster/channasandra.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/mallasandra/2/5 /home/megha/nutrition_ap/cluster/mallasandra.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/marathahalli/2/5 /home/megha/nutrition_ap/cluster/marathahalli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/t%20dasarahalli/2/5 /home/megha/nutrition_ap/cluster/t_dasarahalli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/yashwanthpura/2/5 /home/megha/nutrition_ap/cluster/yashwanthpura.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/yellukunte/2/5 /home/megha/nutrition_ap/cluster/yellukunte.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/abbigere/2/5 /home/megha/nutrition_ap/cluster/abbigere.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/immadihalli/2/5 /home/megha/nutrition_ap/cluster/immadihalli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/jeevan%20bheema%20nagar/2/5 /home/megha/nutrition_ap/cluster/jeevan_bheema_nagar.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/krishnanandanagara/2/5 /home/megha/nutrition_ap/cluster/krishnanandanagara.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/madanayakanahalli/2/5 /home/megha/nutrition_ap/cluster/madanayakanahalli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/ejipura/2/5 /home/megha/nutrition_ap/cluster/ejipura.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/hoodi/2/5 /home/megha/nutrition_ap/cluster/hoodi.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/jalahalli/2/5 /home/megha/nutrition_ap/cluster/jalahalli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/kaggalipura/2/5 /home/megha/nutrition_ap/cluster/kaggalipura.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/kylasanahalli/2/5 /home/megha/nutrition_ap/cluster/kylasanahalli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/sondekoppa/2/5 /home/megha/nutrition_ap/cluster/sondekoppa.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/doddakanneli/2/5 /home/megha/nutrition_ap/cluster/doddakanneli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/varthur/2/5 /home/megha/nutrition_ap/cluster/varthur.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/pghalli/2/5 /home/megha/nutrition_ap/cluster/pghalli.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/4/rajajinagar/2/5 /home/megha/nutrition_ap/cluster/rajajinagar.pdf
#BLOCK
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/5/north-4/2/5 /home/megha/nutrition_ap/block/north-4.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/5/north-3/2/5 /home/megha/nutrition_ap/block/north-3.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/5/north-1/2/5 /home/megha/nutrition_ap/block/north-1.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/5/south-3/2/5 /home/megha/nutrition_ap/block/south-3.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/5/north-2/2/5 /home/megha/nutrition_ap/block/north-2.pdf
phantomjs /home/megha/lib/phantomjs/examples/w2i.js http://dev.klp.org.in:8013/charts/5/south-4/2/5 /home/megha/nutrition_ap/block/south-4.pdf
